def map_code_to_icon(code, is_day):
    if code in [0]: return 'sunny' if is_day else 'clear_night'
    if code in [1, 2, 3]: return 'partly_cloudy_day' if is_day else 'partly_cloudy_night'
    if code in [45, 48]: return 'foggy'
    if code in [51, 53, 55, 56, 57]: return 'rainy_light'
    if code in [61, 63, 65, 66, 67]: return 'rainy'
    if code in [71, 73, 75, 77]: return 'snowing'
    if code in [80, 81, 82]: return 'thunderstorm_showers'
    if code in [85, 86]: return 'heavy_snow'
    if code in [95, 96, 99]: return 'thunderstorm'
    return 'cloud'

def map_code_to_description(code):
    if code == 0: return 'Céu Limpo'
    if code == 1: return 'Principalmente Limpo'
    if code == 2: return 'Parcialmente Nublado'
    if code == 3: return 'Nublado'
    if code in [45, 48]: return 'Névoa'
    if code in [51, 53, 55]: return 'Chuvisco Fraco'
    if code in [61, 63, 65]: return 'Chuva'
    if code in [80, 81, 82]: return 'Aguaceiros'
    if code in [71, 73, 75]: return 'Neve'
    if code in [95, 96, 99]: return 'Trovoada'
    return 'Condição Desconhecida'